splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/nix-config/dotfiles/wallpapers/the-road-to-samarkand.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/nix-config/dotfiles/wallpapers/the-road-to-samarkand.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/nix-config/dotfiles/wallpapers/the-road-to-samarkand.png
    fit_mode = cover
}
